name:                study-category-theory
version:             0.1.0.0
github:              "jwchae8/study-category-theory"
license:             BSD3
author:              "jongwook chae"
maintainer:          "jwchae8@gmail.com"
copyright:           "jongwook"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            study

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jwchae8/study-category-theory#readme>

dependencies:
- base >= 4.7 && < 5
- hspec

library:
  source-dirs: src

executables:
  study-category-theory-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - study-category-theory

tests:
  study-category-theory-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - study-category-theory
